# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=32)),
                ('fechaDeEntrega', models.DateTimeField(blank=True, null=True)),
                ('fechaDeAplazo', models.DateTimeField(blank=True, null=True)),
                ('punteo', models.IntegerField(default=0)),
                ('puteoExtra', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, max_length=224)),
                ('anotaciones', models.TextField(blank=True, max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesProgramadasCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaDeFinalizacion', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=32)),
                ('descripcion', models.TextField(blank=True, max_length=224)),
                ('obejtivos', models.TextField(blank=True, max_length=224)),
                ('materialDeApoyo', models.TextField(blank=True, max_length=512)),
                ('valoracion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=16)),
                ('cel', models.CharField(blank=True, max_length=16)),
                ('direccion', models.TextField(blank=True, max_length=224)),
                ('telEmergencia', models.CharField(blank=True, max_length=16)),
                ('carne', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoEnCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnosEnCurso', to='apiQschool.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=True)),
                ('alumno_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistenciaAlumno', to='apiQschool.AlumnoEnCurso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=32)),
                ('descripcion', models.TextField(blank=True, max_length=2047)),
                ('clase', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primaria', 'primaria'), ('secundaria', 'secundaria'), ('otro', 'otro')], default='secundaria', max_length=16)),
                ('especifico', models.CharField(blank=True, default='.', max_length=32)),
                ('grado', models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto')], default=1, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDePagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noFactura', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('concepto', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('logo3', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('logo4', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('descripcion', models.TextField(blank=True, max_length=2047)),
                ('direccion', models.TextField(blank=True, max_length=224)),
                ('tel1', models.CharField(blank=True, max_length=16)),
                ('tel2', models.CharField(blank=True, max_length=16)),
                ('telefonoDirector', models.CharField(blank=True, max_length=16)),
                ('fechaDePagos', models.DateTimeField(blank=True, null=True)),
                ('mora', models.BooleanField(default=False)),
                ('pagoMensual', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PadreDeFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=16)),
                ('cel', models.CharField(blank=True, max_length=16)),
                ('direccion', models.TextField(blank=True, max_length=224)),
                ('anotaciones', models.CharField(blank=True, max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilPadre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=16)),
                ('cel', models.CharField(blank=True, max_length=16)),
                ('direccion', models.TextField(blank=True, max_length=512)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='apiQschool.Institucion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilProfesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PunteoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comentario', models.TextField(blank=True, max_length=224)),
                ('punteoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='apiQschool.ActividadCurso')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteosAlumno', to='apiQschool.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiQschool.Alumno')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscripciones', to='apiQschool.PadreDeFamilia')),
            ],
        ),
        migrations.AddField(
            model_name='historialdepagos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='apiQschool.Institucion'),
        ),
        migrations.AddField(
            model_name='grado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradosInstitucion', to='apiQschool.Institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursosDeGrado', to='apiQschool.Grado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursosInstitucion', to='apiQschool.Institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursosProfesor', to='apiQschool.Profesor'),
        ),
        migrations.AddField(
            model_name='alumnoencurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CursosDeAlumno', to='apiQschool.Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnosDeGrado', to='apiQschool.Grado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='apiQschool.Institucion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilAlumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadesprogramadascurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa', to='apiQschool.Curso'),
        ),
        migrations.AddField(
            model_name='actividadcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActividadesDeCurso', to='apiQschool.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='subscripciones',
            unique_together=set([('encargado', 'alumno')]),
        ),
        migrations.AlterUniqueTogether(
            name='punteoalumno',
            unique_together=set([('actividad', 'alumno')]),
        ),
    ]
