# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0002_auto_20170715_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='apiQschool.Institucion'),
        ),
    ]
