# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0004_auto_20170715_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcurso',
            name='titulo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='titulo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
