# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0007_horario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistenciaHorario', to='apiQschool.Horario'),
        ),
    ]
