# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0008_asistencia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursosProfesor', to='apiQschool.Perfil'),
        ),
    ]
