# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0011_auto_20170811_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcurso',
            name='imagen',
            field=models.ImageField(default='actividades/imagenes/none.jpg', upload_to='actividades/imagenes/'),
        ),
    ]
