# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0014_auto_20170815_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaactividadalumno',
            name='calificado',
            field=models.BooleanField(default=False),
        ),
    ]
