# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0015_entregaactividadalumno_calificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcurso',
            name='tipo',
            field=models.CharField(blank=True, default='tarea', max_length=64),
        ),
    ]
