# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0016_actividadcurso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcurso',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'tarea'), ('trabajos', 'trabajos'), ('investigacion', 'investigacion'), ('examen parcial', 'examen parcial'), ('examen', 'examen'), ('proyecto', 'proyecto'), ('otro', 'otro')], default='tarea', max_length=64),
        ),
    ]
