# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0017_auto_20170816_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcurso',
            name='punteo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividadcurso',
            name='puteoExtra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='valoracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
