# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0019_auto_20170822_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('punteoExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comentario', models.TextField(blank=True, max_length=224)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='apiQschool.ActividadCurso')),
            ],
        ),
        migrations.RenameField(
            model_name='entregaactividadalumno',
            old_name='comentarioAlumno',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='entregaactividadalumno',
            old_name='calificado',
            new_name='entregado',
        ),
        migrations.RemoveField(
            model_name='entregaactividadalumno',
            name='comentarioProfesor',
        ),
        migrations.RemoveField(
            model_name='entregaactividadalumno',
            name='punteoExtra',
        ),
        migrations.RemoveField(
            model_name='entregaactividadalumno',
            name='valor',
        ),
        migrations.AddField(
            model_name='actividadesprogramadascurso',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaactividadalumno',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaactividadalumno',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='apiQschool.ActividadCurso'),
        ),
    ]
