# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0020_auto_20170823_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcurso',
            name='achivos',
            field=models.BooleanField(default=False),
        ),
    ]
