# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0021_actividadcurso_achivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadcurso',
            old_name='puteoExtra',
            new_name='punteoExtra',
        ),
        migrations.AlterField(
            model_name='actividadcurso',
            name='anotaciones',
            field=models.TextField(blank=True, default='Ninguna', max_length=224),
        ),
    ]
