# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0022_auto_20170823_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadcurso',
            old_name='achivos',
            new_name='archivos',
        ),
    ]
