# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0023_auto_20170823_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcurso',
            name='calificado',
            field=models.BooleanField(default=False),
        ),
    ]
