# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0026_auto_20170828_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='archivo',
            field=models.FileField(null=True, upload_to='actividades/archivos/'),
        ),
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='actividades/imagenes/'),
        ),
    ]
