# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0027_auto_20170829_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades/imagenes/'),
        ),
    ]
