# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0028_auto_20171005_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='actividades/archivos/'),
        ),
    ]
