# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0029_auto_20171005_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, default='Ninguno', max_length=224),
        ),
        migrations.AlterField(
            model_name='entregaactividadalumno',
            name='comentario',
            field=models.TextField(blank=True, default='Ninguno', max_length=224),
        ),
    ]
