# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0031_auto_20171012_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='actividad',
            new_name='entregaActividadAlumno',
        ),
    ]
