# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0032_auto_20171012_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='fechaDeFinalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='fechaDeInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
