# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:14
from __future__ import unicode_literals

import apiQschool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0033_auto_20171019_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo',
            field=models.FileField(blank=True, null=True, upload_to=apiQschool.models.generar_carpeta),
        ),
    ]
