# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 17:29
from __future__ import unicode_literals

import apiQschool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0036_auto_20171023_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo2',
            field=models.FileField(blank=True, null=True, upload_to=apiQschool.models.generar_carpeta),
        ),
        migrations.AddField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo3',
            field=models.FileField(blank=True, null=True, upload_to=apiQschool.models.generar_carpeta),
        ),
    ]
