# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:22
from __future__ import unicode_literals

import apiQschool.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0037_auto_20171026_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialDeApoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apiQschool.models.generar_carpeta)),
                ('actividadProgramada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialesDeApoyo', to='apiQschool.ActividadesProgramadasCurso')),
            ],
        ),
    ]
