# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0038_materialdeapoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo',
        ),
        migrations.RemoveField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo2',
        ),
        migrations.RemoveField(
            model_name='actividadesprogramadascurso',
            name='materialDeApoyo3',
        ),
    ]
