# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0039_auto_20171031_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='fechaDeFinalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadesprogramadascurso',
            name='fechaDeInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
