# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0041_reportes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadesprogramadascurso',
            old_name='obejtivos',
            new_name='objetivos',
        ),
    ]
