# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiQschool', '0045_remove_horario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistenciaAlumno', to='apiQschool.Perfil'),
            preserve_default=False,
        ),
    ]
